### ISSUE TITLE
New AUR package

### ISSUE THREAD

**Issue by Kr1ss-XD** [ston3o/rdcli#33]
Hey @ston3o !

Thank you for this tool. :+1: 
I noticed that you've published it to the AUR. The package still builds v1.3.2 though, and it's flagged as OOD since january.
Rather than submitting an orphan request, I decided to push a ['`rdcli-git`' package](https://aur.archlinux.org/packages/rdcli-git/), so users can install the most recent version from there. I hope you're okay with that; if not pls let me know.
In case you're interested (I do see that you haven't worked on the project for a while), I would happily update your original package to v1.5.1 if you'd add me as co-maintainer for it.

**Comment by ston3o** [comment]
Hello @Kr1ss-XD,

Thanks for notify me ;)

No problem for your package rdcli-git

Free to you to make a PR if you want :)

I would add you as co-maintainer maybe later if necessary.

**Comment by Kr1ss-XD** [comment]
Thank you for your response, and apologies for the delay.

In case you are interested, I've uploaded a patch for your PKGBUILD to a [gist](https://gist.github.com/8b1c91fda6ca3004245bef2861904250), which you could apply to update it.
Otherwise it would be nice if you'd grant me co-maintainership, so that I could update it.

_Cheers !_

**Comment by ston3o** [comment]
Thanks @Kr1ss-XD, I updated AUR package and added you as collaborator of github repository ;)

**Comment by Kr1ss-XD** [comment]
Thanks a lot :+1:
